language: node_js
node_js: lts/*
os:
  - linux
env:
  - NODE_ENV=test
install:
  - rm -rf public src package.json package-lock.json
services:
  - redis-server
  - postgresql
jobs:
  include:
    - stage: Deploy
      script:
        - './script/build.sh'
      deploy:
        provider: heroku
        api_key:
          secure: mHrVN6YKk3EBP3mFBPJvelJ45GhcotYg6iBk6PmHInWnln3oiVBnMUN4pBNbuaW+ubAXzHSLj/Xau4fGWf//gh2eXZDBYOb5355nPN9rup0nhLe4wP46fpxzjO8lS8N9a6kHBpDjCKh/HY5RuLK91MJA4YQJMOp8xr3G/9l5dwgohb1m8yfFkNk0t9y+Cjqcf+pTjxNYKyFyrqUENfO2mSfroMg1WgFvPNk2o46WpqXpYroaon8QDzO9usC+qgqyD9Yja3t/PsVNV7bcw4Bb40NtdiqMuWrpYz0WkQkACjhHXJcz2uLDtD6dqC1VEPdT2ND+zRZvYeA3lJCtJH5Z0nqtveNN23JJUTF1lpregbkEFE7nUNiVsrCNnsrE3dloijg1UDFKW/i5eoR9u8QHMv/45IB5kkfBwLvtXX5Of3lwyj8ItvBRYRj4OyUTOEbYxAC4knw84Z5jBlL6ZNSdWqB0AOpY0En6uyjCQTRPPQQEfUZfJ7lSJJAXNIXUcGsE5NHdam6H8v04ERKMzGl78KMCAhw6ekHcu7Gg4ielmo6BN+kJpXzN41XBKWMezzP2owFyF8ZawzelN/VstsK7hE+PtFbQSsu8AIedTTzVBTElarF20pbv3XDVkSiv/DBF1OvZJUpBWbRlKK5KB9dJJ3vzy1F5Xtc6HZzHFwuRuqE=
        skip_cleanup: true
        app: give-feedback
        run: restart
