language: node_js
node_js: lts/*
os:
  - linux
env:
  - NODE_ENV=test
install:
  - rm -rf public src package.json package-lock.json
services:
  - redis-server
  - postgresql
jobs:
  include:
    - stage: Deploy
      script:
        - './script/build.sh'
      deploy:
        provider: heroku
        api_key:
          secure: XmoP2/p3kIaKHhXFOoaEUgewW/u6eWMKYcg8bJwKot+uW7Mn+K/jMRCW7MSUSaJTnL0JMv8i0KyUUH4MPryOmvuqElI6BGPUCuxycl5zSFHp1pt0HhIBOC3o1vJG36c5q6XMLMaxH9FQvSDHaUTkpwY5miilRJLwkWVS+Xu3pG4OgxjmadU4tlhO6FnbuXWOZP2rTfQeLkVFHBqQQO1I1KbzA4tTiodnKmQ/oC3GYdgQ9rqzpmsjLTB6VaZeYZkZ200FsTLG4by6zD2Xo0pGLmaK+lB3+HGkmpuB4GXBysR0rE4Jx7v4FCFnOnN5GzE4jIc1B3k7Fcc/u0rQm/h89sZGWIo+FaIvWC9Wc4R0xfFhOCkPh4CUKTcWYIOjTEnBQ+yZ7ULAYUoL+NQUO5nGdqtbnTeS7bq6+v6s/m0UOmAir1rtAoJwBakvqACKCwoVD9fB/XofPLWs/IOXGVe3G2v49OoFGmHipq5Z+/ie1XFuTPBQawJB8sg0yxIRqI1WqO4IF66Wu1xXu6gDeeZZNEXYq9fNsD7r6QNutzNemsCuZcgrULwF4ImStCkHJNOHx0HOMw6N2V6ND0JR3piv//LmCIyBANcYYsJVpPgiPhOOKZE68ejTzbGZmr8yYTV2y4cdlW2PnR4nyJ/BihQJ9UPpj0KRS/SIep6RnAV0voQ=
        skip_cleanup: true
        app: give-feedback
        run: restart
