language: node_js
node_js: lts/*
os:
  - linux
env:
  - NODE_ENV=test
install:
  - rm -rf public src package.json package-lock.json
services:
  - redis-server
  - postgresql
jobs:
  include:
    - stage: Deploy
      script:
        - './script/build.sh'
      deploy:
        provider: heroku
        api_key:
          secure: P3+MVIMqd+1NkuO6mT7npQdWGiQ70vrQhei39U+mILs5l1O4enGejWXIjAJ+TVyJaYqgeZCxHfhKsUx/gHbOCfE1bgLz19mKTsoSrA4jZ8u6DQeeaftZ+99dRewGeaPqvBb5M+FgHuxaveWgG29dupoPwZKCPnn+TsF+t4A9rWb2hoFhWyFYv/nIvof/S1MJUB6lVHZOxbEFm6vDYoQ9vIp1b3loWHjo1cyLwXHl8YCzhWW1Hk9h7dCDbnvB6epsWqx5XX5o7C0FAchm29Lni/oeNCph2KL6x1m40FNlRdfr8mclDLpBNns5te4BZAfVd6aCb0TI0gj9yWVT49FhoJM54kpu8qZPL5aR8uQhf8kdXnCUbc9odGMzxoeOD9yf5k5JDuJePI8Ysdc9Kj8C/FR6WwYgD4IOEPEasBJwjiflVVXU+fYCnwoFd8/1l7OLopwS1yghiKtOS2aQtPLNjV2zp1r88crSs5Q8IkrIZIFca4/ussb+ouGTP2qYBbdSVyX21zK7avE1wQJAcSPoouI+xq+TUJliYjW0hubhOjyQ/fQ9K753PPLbD1CaakbN16ubAC4Oeu/X1YVQkrxsRpXWkRX0+hEzNhnfK/lclCfRgbSm56uXguO1ZSwmF7F0b9h9THRSD3aY2jOFoM3UXKtF1HHCWr4BF1mXnhS/Xg8=
        skip_cleanup: true
        app: give-feedback
        run: restart
